apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  externalIPs:
  - 80.11.12.10
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# if service stuck on pending state then assign it one by:
  # externalIPs:
  # - 80.11.12.10