apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    # means the capacity of storage you want available
    storage: 1Gi
  volumeMode: Filesystem # or Block
  # now you have a persisted volume
  storageClassName: standard
  accessModes:
    # this works because of our 1 pod minikube
    - ReadWriteOnce
    # means can be claimed by many nodes - when working with multiple nodes
    # - ReadOnlyMany
    # same with this works with multiple nodes
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate